"""remove unnecessary tables

Revision ID: 2358a46a1805
Revises: 0cb38d445403
Create Date: 2026-02-14 16:26:12.192320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2358a46a1805'
down_revision: Union[str, Sequence[str], None] = '0cb38d445403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course_crosslist')
    op.drop_table('clubs')
    op.drop_table('crosslist_groups')
    op.drop_table('schedule_categories')
    op.drop_table('careers')
    op.drop_table('academics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academics',
    sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('course_num', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('course_name', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('instructors', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('academics_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('academics_pkey'))
    )
    op.create_table('careers',
    sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('host', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('registration_required', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('careers_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('careers_pkey'))
    )
    op.create_table('schedule_categories',
    sa.Column('schedule_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('category_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('schedule_categories_category_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], name=op.f('schedule_categories_schedule_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id', 'category_id', name=op.f('schedule_categories_pkey'))
    )
    op.create_table('crosslist_groups',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='crosslist_groups_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('clubs',
    sa.Column('event_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('clubs_event_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('clubs_pkey'))
    )
    op.create_table('course_crosslist',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('group_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name=op.f('course_crosslist_course_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['crosslist_groups.id'], name=op.f('course_crosslist_group_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('course_crosslist_pkey'))
    )
    # ### end Alembic commands ###
