"""add agent run to events

Revision ID: 55da73f9050c
Revises: 2358a46a1805
Create Date: 2026-02-21 15:39:56.876787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55da73f9050c'
down_revision: Union[str, Sequence[str], None] = '2358a46a1805'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('agent_run_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key('events_agent_run_id_fkey', 'events', 'agent_runs', ['agent_run_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_agent_run_id_fkey', 'events', type_='foreignkey')
    op.drop_column('events', 'agent_run_id')
    # ### end Alembic commands ###
